/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Character = IDL.Record({
  'id' : IDL.Nat,
  'gameSystem' : IDL.Text,
  'name' : IDL.Text,
  'race' : IDL.Text,
  'archetype' : IDL.Text,
  'gender' : IDL.Text,
  'avatarId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createCharacter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getCharacter' : IDL.Func([IDL.Nat], [Character], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Character = IDL.Record({
    'id' : IDL.Nat,
    'gameSystem' : IDL.Text,
    'name' : IDL.Text,
    'race' : IDL.Text,
    'archetype' : IDL.Text,
    'gender' : IDL.Text,
    'avatarId' : IDL.Nat,
  });
  
  return IDL.Service({
    'createCharacter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteCharacter' : IDL.Func([IDL.Nat], [], []),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getCharacter' : IDL.Func([IDL.Nat], [Character], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };